feat: временно закомментировать конфигурацию тестов в GitHub Actions для упрощения отладки

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -10,58 +10,58 @@ on:
       - 'composer.lock'
 
 jobs:
-  test:
-    runs-on: ubuntu-latest
-    timeout-minutes: 5
-    strategy:
-      fail-fast: true
-      matrix:
-        php: [8.4, 8.3, 8.1]
-        laravel: [12.*, 11.*, 10.*]
-        stability: [prefer-stable]
-        include:
-          - laravel: 12.*
-            testbench: 10.*
-          - laravel: 11.*
-            testbench: 9.*
-          - laravel: 10.*
-            testbench: 8.*
-        exclude:
-          - laravel: 10.*
-            php: 8.4
-          - laravel: 11.*
-            php: 8.1
-          - laravel: 12.*
-            php: 8.1
+  # test:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 5
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       php: [8.4, 8.3, 8.1]
+  #       laravel: [12.*, 11.*, 10.*]
+  #       stability: [prefer-stable]
+  #       include:
+  #         - laravel: 12.*
+  #           testbench: 10.*
+  #         - laravel: 11.*
+  #           testbench: 9.*
+  #         - laravel: 10.*
+  #           testbench: 8.*
+  #       exclude:
+  #         - laravel: 10.*
+  #           php: 8.4
+  #         - laravel: 11.*
+  #           php: 8.1
+  #         - laravel: 12.*
+  #           php: 8.1
 
-    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}
+  #   name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Setup PHP
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: ${{ matrix.php }}
-          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
-          coverage: none
+  #     - name: Setup PHP
+  #       uses: shivammathur/setup-php@v2
+  #       with:
+  #         php-version: ${{ matrix.php }}
+  #         extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
+  #         coverage: none
 
-      - name: Setup problem matchers
-        run: |
-          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
-          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
+  #     - name: Setup problem matchers
+  #       run: |
+  #         echo "::add-matcher::${{ runner.tool_cache }}/php.json"
+  #         echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
 
-      - name: Install dependencies
-        run: |
-          composer require "laravel/framework:${{ matrix.laravel }}.*" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
-          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
+  #     - name: Install dependencies
+  #       run: |
+  #         composer require "laravel/framework:${{ matrix.laravel }}.*" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
+  #         composer update --${{ matrix.stability }} --prefer-dist --no-interaction
 
-      - name: List Installed Dependencies
-        run: composer show -D
+  #     - name: List Installed Dependencies
+  #       run: composer show -D
 
-      - name: Execute tests
-        run: vendor/bin/pest --ci
+  #     - name: Execute tests
+  #       run: vendor/bin/pest --ci
 
   install:
     runs-on: ubuntu-latest
@@ -71,7 +71,7 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        php: [8.4, 8.3, 8.1]
+        php: [8.4, 8.1]
         laravel: [12, 11, 10]
         exclude:
           - laravel: 10
@@ -94,6 +94,9 @@ jobs:
           composer create-project "laravel/laravel:^${{ matrix.laravel }}.0" .
           composer require spatie/laravel-health gocpa/space-healthcheck:dev-new-version
           echo "<?php return ['result_stores' => [Spatie\Health\ResultStores\CacheHealthResultStore::class => ['store' => 'file']]];" > config/health.php
+          # echo "<?php namespace App\Providers; class HealthServiceProvider extends \Illuminate\Support\ServiceProvider { public function boot(): void { \Spatie\Health\Facades\Health::checks([\Spatie\Health\Checks\Checks\DebugModeCheck::new()]); } }" > app/Providers/HealthServiceProvider.php
+          cat app/Providers/AppServiceProvider.php
+          exit 1
           git config --global init.defaultBranch master
           git config --global user.email "you@example.com"
           git config --global user.name "Your Name"
